# Generated by Django 4.1 on 2022-09-01 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesireUser',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='criado_em')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='modificado_em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Concluido'), (3, 'Cancelado')])),
                ('desire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desire')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
            bases=('core.auditmodel', models.Model),
        ),
    ]
