# Generated by Django 4.1 on 2022-09-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desireuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Concluido'), (3, 'Cancelado')], default=1),
        ),
    ]
