# Generated by Django 4.1 on 2022-08-31 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_job_alter_desire_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExec',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='criado_em')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='modificado_em')),
                ('percent_done', models.FloatField(verbose_name='percentual_realizado')),
                ('desire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desire')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.auditmodel', models.Model),
        ),
    ]
