# Generated by Django 4.1 on 2022-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexec',
            options={'verbose_name': 'movimento', 'verbose_name_plural': 'movimentos'},
        ),
        migrations.AddField(
            model_name='jobexec',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
