# Generated by Django 4.1 on 2022-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexec',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='descrição'),
        ),
    ]
